'use client';

import { Popover, PopoverContent, PopoverTrigger } from '@workspace/ui/components/popover';
// import { Avatar, AvatarFallback, AvatarImage } from '@workspace/ui/components/avatar';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@workspace/ui/components/card';
import { Button } from '@workspace/ui/components/button';
// import { useConnectWallet, useCurrentAccount, useWallets } from '@mysten/dapp-kit';
// import { isEnokiWallet, AuthProvider } from '@mysten/enoki';
// import { type EnokiWallet } from '@mysten/enoki';
// import Link from 'next/link';
import { useCustomWallet } from '@/contexts/CustomWallet';
import { useEffect, useState } from 'react';
import { ExternalLink, Trophy } from 'lucide-react';
import Link from 'next/link';

export default function Page() {
  const [mounted, setMounted] = useState(false);
  const {
    isConnected,
    isUsingEnoki,
    address,
    jwt,
    emailAddress,
    getAddressSeed,
    executeTransactionBlockWithoutSponsorship,
    signAndExecuteTransaction,
    logout,
    redirectToAuthUrl,
  } = useCustomWallet();

  useEffect(() => {
    setMounted(true);
  }, []);

  // Ensure page can scroll
  useEffect(() => {
    document.body.style.overflow = 'auto';
    document.documentElement.style.overflow = 'auto';
    
    return () => {
      document.body.style.overflow = '';
      document.documentElement.style.overflow = '';
    };
  }, []);

  useEffect(() => {
    if (mounted && isConnected) {
      (window as any).customWallet = {
        isConnected,
        isUsingEnoki,
        address,
        jwt,
        emailAddress,
        executeTransactionBlockWithoutSponsorship,
        signAndExecuteTransaction,
        logout,
        redirectToAuthUrl,
        getAddressSeed,
      };
    }
  }, [
    mounted,
    isConnected,
    isUsingEnoki,
    address,
    jwt,
    emailAddress,
    executeTransactionBlockWithoutSponsorship,
    signAndExecuteTransaction,
    logout,
    redirectToAuthUrl,
    getAddressSeed,
  ]);

  if (!mounted) {
    return null;
  }

  return (
    <div className="bg-[#0a0b17] text-white" style={{ height: 'auto', minHeight: '100vh', overflowY: 'visible' }}>
      {/* 顶部导航栏 */}
      <header className="w-full py-3 px-6 flex justify-between items-center z-10 sticky top-0 bg-[#0a1525] border-b border-gray-800">
        <div className="text-xl font-bold text-yellow-300">NUMERON</div>
        <div className="flex items-center space-x-4">
        <nav className="flex items-center space-x-4">
        <Link 
            href="/chat" 
            className="text-gray-300 hover:text-yellow-300 transition-colors"
          >
            AI
          </Link>
          <Link 
            href="/market" 
            className="text-gray-300 hover:text-yellow-300 transition-colors"
          >
            Marketplace
          </Link>
          <Link 
            href="/box" 
            className="text-gray-300 hover:text-yellow-300 transition-colors"
          >
            Box
          </Link>
        </nav>
        <Link href="/ranking" className="flex items-center p-3 rounded-lg bg-[#0a1525] border border-gray-800 hover:border-gray-700 transition-all">
          <div className="w-10 h-10 rounded-full bg-yellow-900/30 flex items-center justify-center mr-3">
            <Trophy className="h-5 w-5 text-yellow-400" />
          </div>
          <div>
            <h3 className="font-bold">Ranking</h3>
          </div>
        </Link>
          {/* <div className="relative group">
            <button className="text-white text-sm hover:text-yellow-300 flex items-center">
              COMMUNITY <span className="ml-1">▼</span>
            </button>
          </div>
          <div className="relative group">
            <button className="text-white text-sm hover:text-yellow-300 flex items-center">
              ABOUT <span className="ml-1">▼</span>
            </button>
          </div> */}
          {isConnected ? (
            <Popover>
              <PopoverTrigger asChild>
                <Button className="bg-green-500 text-white text-sm px-4 py-1 rounded-full font-medium">
                  {emailAddress ? emailAddress : `${address?.slice(0, 5)}...${address?.slice(63)}`}
                </Button>
              </PopoverTrigger>
              <PopoverContent>
                <Card className="border-none shadow-none">
                  <CardHeader>
                    <CardTitle>Account Information</CardTitle>
                    <CardDescription>View account generated by Enoki's zkLogin process.</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <>
                      <div className="flex flex-row gap-1 items-center">
                        <span>Address: </span>
                        <div className="flex flex-row gap-1">
                          <span>{`${address?.slice(0, 5)}...${address?.slice(63)}`}</span>
                          <a href={`https://suiscan.xyz/testnet/account/${address}`} target="_blank" rel="noreferrer">
                            <ExternalLink width={12} />
                          </a>
                        </div>
                      </div>
                    </>
                  </CardContent>
                  <CardFooter className="flex flex-row gap-2 items-center justify-between">
                    <Button variant={'destructive'} size={'sm'} className="w-full text-center" onClick={logout}>
                      Logout
                    </Button>
                  </CardFooter>
                </Card>
              </PopoverContent>
            </Popover>
          ) : (
            <Button 
              className="bg-yellow-400 text-black text-sm px-4 py-1 rounded-full font-medium"
              onClick={() => {
                redirectToAuthUrl();
              }}
            >
              Login
            </Button>
          )}
        </div>
      </header>

      {/* 主要内容区域 */}
      <main className="flex-1 flex flex-col px-2 sm:px-4" style={{ minHeight: '100%', overflowY: 'visible' }}>
        {/* 顶部轮播区域 - 调整边框和样式 */}
        <div className="relative w-full max-w-5xl mx-auto mt-4 mb-6 rounded-xl overflow-hidden border border-purple-500/30">
          <div className="bg-[#0a2040] h-[200px] sm:h-[300px] relative">
            {/* Carousel Content - Insert Image */}
            <img 
              src="/home.png" 
              alt="Home Preview" 
              className="absolute inset-0 w-full h-full object-contain rounded-xl pointer-events-none select-none" 
              style={{ zIndex: 1 }}
            />
            <div className="absolute left-4 bottom-4 z-10">
              <Link href="/game">
                <Button className="bg-gray-400/20 hover:bg-gray-400/30 text-white text-xs px-4 py-1.5 rounded-md w-full sm:w-auto">
                  Start Game
                </Button>
              </Link>
            </div>
          </div>
        </div>


        {/* 支持者和构建信息 - 调整间距和样式 */}
        <div className="text-center mb-6">
          <p className="text-xs text-gray-400">Support By</p>
          <div className="flex justify-center items-center space-x-4 my-2">
          <img src="/mediakit/merak/png/b.png" alt="Merak Logo" className="h-8 w-auto" />
          <img src="/mediakit/phad/phad.png" alt="PHAD Logo" className="h-8 w-auto" />
          <img src="/mediakit/obelisklabs/logo1/1.png" alt="Obelisk Labs Logo" className="h-20 w-auto" />
          </div>
          
          <p className="text-xs text-gray-400 mt-4">Build On</p>
          <div className="flex justify-center items-center space-x-4 my-2">
            <img src="/mediakit/dubhe/png/b.png" alt="Dubhe Logo" className="h-8 w-auto" />
            <img src="/mediakit/sui/Sui Logo White/Sui_Logo_White.png" alt="Sui Logo" className="h-8 w-auto" />
          </div>
        </div>

        {/* 游戏列表区域 - 仪表盘风格卡片 响应式 */}
        <div className="w-full max-w-5xl mx-auto mb-12">
          <div className="text-center mb-6 relative">
            <div className="absolute left-0 right-0 top-1/2 h-px bg-gray-700"></div>
            <span className="relative bg-[#0a0b17] px-6 text-sm">ALL DATA</span>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            {/* Card 1 */}
            <div className="bg-[#18181b] rounded-lg p-6 flex flex-col justify-between shadow border border-gray-800">
              <div className="text-gray-400 text-xs font-semibold mb-2 flex items-center gap-2">
                CURRENT PRICE
                <span className="ml-auto">
                  <svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="8" cy="8" r="7"/><path d="M8 4v4l2 2"/></svg>
                </span>
              </div>
              <div className="text-2xl font-bold text-white">$0.038</div>
              <div className="text-green-400 text-xs mt-1">+1.18%</div>
            </div>
            {/* Card 2 */}
            <div className="bg-[#18181b] rounded-lg p-6 flex flex-col justify-between shadow border border-gray-800">
              <div className="text-gray-400 text-xs font-semibold mb-2 flex items-center gap-2">
                ACTIVE MAPS
                <span className="ml-auto">
                  <svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="10" height="10" rx="2"/></svg>
                </span>
              </div>
              <div className="text-2xl font-bold text-white">6</div>
            </div>
            {/* Card 3 */}
            <div className="bg-[#18181b] rounded-lg p-6 flex flex-col justify-between shadow border border-gray-800">
              <div className="text-gray-400 text-xs font-semibold mb-2 flex items-center gap-2">
                NUM STAKED
                <span className="ml-auto">
                  <svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="2" y="6" width="12" height="8" rx="2"/><path d="M6 10V6a2 2 0 1 1 4 0v4"/></svg>
                </span>
              </div>
              <div className="text-2xl font-bold text-white">13,410,997.781</div>
              <div className="text-green-400 text-xs mt-1">+5.2%</div>
            </div>
            {/* Card 4 */}
            <div className="bg-[#18181b] rounded-lg p-6 flex flex-col justify-between shadow border border-gray-800">
              <div className="text-gray-400 text-xs font-semibold mb-2 flex items-center gap-2">
                CURRENT APY
                <span className="ml-auto">
                  <svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12l2-2 4 4 8-8"/></svg>
                </span>
              </div>
              <div className="text-2xl font-bold text-white">13.3%</div>
            </div>
            {/* Card 5 */}
            <div className="bg-[#18181b] rounded-lg p-6 flex flex-col justify-between shadow border border-gray-800">
              <div className="text-gray-400 text-xs font-semibold mb-2 flex items-center gap-2">
                MARKET CAP
                <span className="ml-auto">
                  <svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12h3v4H3zM9 8h3v8H9zM15 4h3v12h-3z"/></svg>
                </span>
              </div>
              <div className="text-2xl font-bold text-white">$7,784,677.871</div>
              <div className="text-green-400 text-xs mt-1">+49.42%</div>
            </div>
            {/* Card 6 */}
            <div className="bg-[#18181b] rounded-lg p-6 flex flex-col justify-between shadow border border-gray-800">
              <div className="text-gray-400 text-xs font-semibold mb-2 flex items-center gap-2">
                24H VOLUME
                <span className="ml-auto">
                  <svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="8" cy="8" r="7"/><path d="M8 4v4l2 2"/></svg>
                </span>
              </div>
              <div className="text-2xl font-bold text-white">$17,709.264</div>
              <div className="text-green-400 text-xs mt-1">+298.18%</div>
            </div>
            {/* Card 7 */}
            <div className="bg-[#18181b] rounded-lg p-6 flex flex-col justify-between shadow border border-gray-800">
              <div className="text-gray-400 text-xs font-semibold mb-2 flex items-center gap-2">
                7D CHANGE
                <span className="ml-auto">
                  <svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12h3v4H3zM9 8h3v8H9zM15 4h3v12h-3z"/></svg>
                </span>
              </div>
              <div className="text-2xl font-bold text-white">49.42%</div>
              <div className="text-green-400 text-xs mt-1">+49.42%</div>
            </div>
            {/* Card 8 - Interactions */}
            <div className="bg-[#18181b] rounded-lg p-6 flex flex-col justify-between shadow border border-gray-800">
              <div className="text-gray-400 text-xs font-semibold mb-2 flex items-center gap-2">
                INTERACTIONS
                <span className="ml-auto">
                  <svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 4v5h.582M20 20v-5h-.581M5 9A7 7 0 0 1 20 15.5M19 15A7 7 0 0 1 4 8.5"/></svg>
                </span>
              </div>
              <div className="text-2xl font-bold text-white">1,234,567</div>
              <div className="text-green-400 text-xs mt-1">+12.5%</div>
            </div>
          </div>
        </div>
        
        {/* Token Distribution 响应式卡片 */}
        <div className="w-full max-w-3xl mx-auto mb-16 px-2 sm:px-4 flex flex-col items-center">
          <div className="bg-[#18181b] rounded-xl shadow-lg p-4 sm:p-8 w-full flex flex-col items-center">
            <h2 className="text-2xl sm:text-3xl font-bold text-white mb-2 text-center">Token Distribution</h2>
            <div className="text-gray-300 text-base sm:text-lg mb-4 sm:mb-6 text-center">Supply: 100,000,000 NUM</div>
            {/* Pie Chart SVG */}
            <svg width="100%" height="180" viewBox="0 0 36 36" className="mb-6 max-w-[180px] w-full h-auto">
              <circle cx="18" cy="18" r="16" fill="#fff" opacity="0.1" />
              <path d="M18 2 a 16 16 0 0 1 13.856 8.001" fill="none" stroke="#5c443b" strokeWidth="4" strokeDasharray="44.8 55.2" strokeDashoffset="0" />
              <path d="M31.856 10.001 A 16 16 0 0 1 25.856 29.856" fill="none" stroke="#ffe2a9" strokeWidth="4" strokeDasharray="39.6 60.4" strokeDashoffset="44.8" />
              <path d="M25.856 29.856 A 16 16 0 0 1 10.144 29.856" fill="none" stroke="#e6e6e6" strokeWidth="4" strokeDasharray="16.2 83.8" strokeDashoffset="84.4" />
              <path d="M10.144 29.856 A 16 16 0 0 1 18 2" fill="none" stroke="#f7d7a0" strokeWidth="4" strokeDasharray="19.4 80.6" strokeDashoffset="100.6" />
            </svg>
            {/* Legend */}
            <div className="flex flex-col gap-2 w-full max-w-md mx-auto text-sm sm:text-lg">
              <div className="flex justify-between items-center text-gray-200">
                <span className="flex items-center gap-2"><span className="w-4 h-4 rounded-full inline-block" style={{background:'#5c443b'}}></span>Staking Rewards</span>
                <span className="font-bold">40%</span>
              </div>
              <div className="flex justify-between items-center text-gray-200">
                <span className="flex items-center gap-2"><span className="w-4 h-4 rounded-full inline-block" style={{background:'#ffe2a9'}}></span>Game Rewards</span>
                <span className="font-bold">35%</span>
              </div>
              <div className="flex justify-between items-center text-gray-200">
                <span className="flex items-center gap-2"><span className="w-4 h-4 rounded-full inline-block" style={{background:'#e6e6e6'}}></span>Development</span>
                <span className="font-bold">15%</span>
              </div>
              <div className="flex justify-between items-center text-gray-200">
                <span className="flex items-center gap-2"><span className="w-4 h-4 rounded-full inline-block" style={{background:'#f7d7a0'}}></span>Community</span>
                <span className="font-bold">10%</span>
              </div>
            </div>
          </div>
        </div>
      </main>
      
      {/* 页脚 - 调整为更贴近设计稿 */}
      <footer className="w-full py-6 px-2 sm:px-6 bg-[#0a1525] mt-auto">
        <div className="max-w-5xl mx-auto flex flex-col md:flex-row justify-between items-center gap-2 flex-wrap">
          <div className="mb-2 md:mb-0">
            <div className="text-lg font-bold text-yellow-300">NUMERON</div>
            <div className="text-xs text-gray-400 mt-1">© {new Date().getFullYear()} Numeron OS</div>
          </div>
          
          <div className="flex space-x-4 flex-wrap">
            <a href="#" className="text-gray-400 hover:text-white">
              <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path>
              </svg>
            </a>
            <a href="#" className="text-gray-400 hover:text-white">
              <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path>
              </svg>
            </a>
            <a href="#" className="text-gray-400 hover:text-white">
              <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="10"></circle>
                <circle cx="12" cy="12" r="4"></circle>
                <line x1="4.93" y1="4.93" x2="9.17" y2="9.17"></line>
                <line x1="14.83" y1="14.83" x2="19.07" y2="19.07"></line>
                <line x1="14.83" y1="9.17" x2="19.07" y2="4.93"></line>
                <line x1="4.93" y1="19.07" x2="9.17" y2="14.83"></line>
              </svg>
            </a>
            <a href="#" className="text-gray-400 hover:text-white">
              <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path>
              </svg>
            </a>
          </div>
        </div>
      </footer>
    </div>
  );
}

