  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module numeron::item_dropped {

  use sui::bcs::{to_bytes};

  use std::ascii::{string, String, into_bytes};

  use dubhe::table_id;

  use dubhe::dapp_service::{Self, DappHub};

  use dubhe::dapp_system;

  use numeron::dapp_key;

  use numeron::dapp_key::DappKey;

  use numeron::item_type;

  use numeron::item_type::{ItemType};

  const TABLE_NAME: vector<u8> = b"item_dropped";

  const TABLE_TYPE: vector<u8> = b"Resource";

  const OFFCHAIN: bool = true;

  public struct ItemDropped has copy, drop, store {
    player: String,
    item_type: ItemType,
  }

  public fun new(player: String, item_type: ItemType): ItemDropped {
    ItemDropped {
            player,
            item_type,
        }
  }

  public fun player(self: &ItemDropped): String {
    self.player
  }

  public fun item_type(self: &ItemDropped): ItemType {
    self.item_type
  }

  public fun update_player(self: &mut ItemDropped, player: String) {
    self.player = player
  }

  public fun update_item_type(self: &mut ItemDropped, item_type: ItemType) {
    self.item_type = item_type
  }

  public fun get_table_id(): String {
    string(TABLE_NAME)
  }

  public fun get_key_schemas(): vector<String> {
    vector[]
  }

  public fun get_value_schemas(): vector<String> {
    vector[string(b"String"),
    string(b"ItemType")
    ]
  }

  public fun get_key_names(): vector<String> {
    vector[]
  }

  public fun get_value_names(): vector<String> {
    vector[string(b"player"),
    string(b"item_type")
    ]
  }

  public(package) fun register_table(dapp_hub: &mut DappHub, ctx: &mut TxContext) {
    let dapp_key = dapp_key::new();
    dapp_system::register_table(
            dapp_hub,
             dapp_key,
            string(TABLE_TYPE),
            get_table_id(), 
            get_key_schemas(), 
            get_key_names(), 
            get_value_schemas(), 
            get_value_names(), 
            OFFCHAIN,
            ctx
        );
  }

  public(package) fun set(dapp_hub: &mut DappHub, player: String, item_type: ItemType) {
    let key_tuple = vector::empty();
    let value_tuple = encode(player, item_type);
    dapp_system::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple, OFFCHAIN);
  }

  public(package) fun set_struct(dapp_hub: &mut DappHub, item_dropped: ItemDropped) {
    let key_tuple = vector::empty();
    let value_tuple = encode_struct(item_dropped);
    dapp_system::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple, OFFCHAIN);
  }

  public fun encode(player: String, item_type: ItemType): vector<vector<u8>> {
    let mut value_tuple = vector::empty();
    value_tuple.push_back(to_bytes(&into_bytes(player)));
    value_tuple.push_back(numeron::item_type::encode(item_type));
    value_tuple
  }

  public fun encode_struct(item_dropped: ItemDropped): vector<vector<u8>> {
    encode(item_dropped.player, item_dropped.item_type)
  }
}
