  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module numeron::errors {

  #[error]

  const NOT_REGISTERED: vector<u8> = b"This player is not registered";

  public fun not_registered_error(condition: bool) {
    assert!(condition, NOT_REGISTERED)
  }

  #[error]

  const INVALID_DIRECTION: vector<u8> = b"Invalid direction";

  public fun invalid_direction_error(condition: bool) {
    assert!(condition, INVALID_DIRECTION)
  }
}
