  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module numeron::numeron_item_metadata {

  use std::ascii::String;

  use numeron::numeron_item_type::ItemType;

  public struct ItemMetadata has copy, drop, store {
    item_type: ItemType,
    icon_url: String,
    name: String,
    description: String,
    is_transferable: bool,
  }

  public fun new(
    item_type: ItemType,
    icon_url: String,
    name: String,
    description: String,
    is_transferable: bool,
  ): ItemMetadata {
    ItemMetadata {
                                   item_type,icon_url,name,description,is_transferable
                               }
  }

  public fun get(self: &ItemMetadata): (ItemType,String,String,String,bool) {
    (self.item_type,self.icon_url,self.name,self.description,self.is_transferable)
  }

  public fun get_item_type(self: &ItemMetadata): ItemType {
    self.item_type
  }

  public fun get_icon_url(self: &ItemMetadata): String {
    self.icon_url
  }

  public fun get_name(self: &ItemMetadata): String {
    self.name
  }

  public fun get_description(self: &ItemMetadata): String {
    self.description
  }

  public fun get_is_transferable(self: &ItemMetadata): bool {
    self.is_transferable
  }

  public(package) fun set_item_type(self: &mut ItemMetadata, item_type: ItemType) {
    self.item_type = item_type;
  }

  public(package) fun set_icon_url(self: &mut ItemMetadata, icon_url: String) {
    self.icon_url = icon_url;
  }

  public(package) fun set_name(self: &mut ItemMetadata, name: String) {
    self.name = name;
  }

  public(package) fun set_description(self: &mut ItemMetadata, description: String) {
    self.description = description;
  }

  public(package) fun set_is_transferable(self: &mut ItemMetadata, is_transferable: bool) {
    self.is_transferable = is_transferable;
  }

  public(package) fun set(
    self: &mut ItemMetadata,
    item_type: ItemType,
    icon_url: String,
    name: String,
    description: String,
    is_transferable: bool,
  ) {
    self.item_type = item_type;
    self.icon_url = icon_url;
    self.name = name;
    self.description = description;
    self.is_transferable = is_transferable;
  }
}
