  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module numeron::numeron_item_type {

  public enum ItemType has copy, drop , store {
                                Ball,Currency,Food,Medicine,Material,SkillBook,Scroll,TreasureChest
                        }

  public fun new_ball(): ItemType {
    ItemType::Ball
  }

  public fun new_currency(): ItemType {
    ItemType::Currency
  }

  public fun new_food(): ItemType {
    ItemType::Food
  }

  public fun new_medicine(): ItemType {
    ItemType::Medicine
  }

  public fun new_material(): ItemType {
    ItemType::Material
  }

  public fun new_skill_book(): ItemType {
    ItemType::SkillBook
  }

  public fun new_scroll(): ItemType {
    ItemType::Scroll
  }

  public fun new_treasure_chest(): ItemType {
    ItemType::TreasureChest
  }
}
