  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module numeron::numeron_item {

  use std::ascii::String;

  public struct Item has copy, drop, store {
    id: u256,
    quantities: u256,
  }

  public fun new(id: u256, quantities: u256): Item {
    Item {
                                   id,quantities
                               }
  }

  public fun get(self: &Item): (u256,u256) {
    (self.id,self.quantities)
  }

  public fun get_id(self: &Item): u256 {
    self.id
  }

  public fun get_quantities(self: &Item): u256 {
    self.quantities
  }

  public(package) fun set_id(self: &mut Item, id: u256) {
    self.id = id;
  }

  public(package) fun set_quantities(self: &mut Item, quantities: u256) {
    self.quantities = quantities;
  }

  public(package) fun set(self: &mut Item, id: u256, quantities: u256) {
    self.id = id;
    self.quantities = quantities;
  }
}
