  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module numeron::numeron_map_config {

  use std::ascii::String;

  public struct MapConfig has copy, drop, store {
    width: u64,
    height: u64,
    background: String,
  }

  public fun new(width: u64, height: u64, background: String): MapConfig {
    MapConfig {
                                   width,height,background
                               }
  }

  public fun get(self: &MapConfig): (u64,u64,String) {
    (self.width,self.height,self.background)
  }

  public fun get_width(self: &MapConfig): u64 {
    self.width
  }

  public fun get_height(self: &MapConfig): u64 {
    self.height
  }

  public fun get_background(self: &MapConfig): String {
    self.background
  }

  public(package) fun set_width(self: &mut MapConfig, width: u64) {
    self.width = width;
  }

  public(package) fun set_height(self: &mut MapConfig, height: u64) {
    self.height = height;
  }

  public(package) fun set_background(self: &mut MapConfig, background: String) {
    self.background = background;
  }

  public(package) fun set(self: &mut MapConfig, width: u64, height: u64, background: String) {
    self.width = width;
    self.height = height;
    self.background = background;
  }
}
