  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module numeron::numeron_position {

  use std::ascii::String;

  public struct Position has copy, drop, store {
    map_id: u64,
    x: u64,
    y: u64,
  }

  public fun new(map_id: u64, x: u64, y: u64): Position {
    Position {
                                   map_id,x,y
                               }
  }

  public fun get(self: &Position): (u64,u64,u64) {
    (self.map_id,self.x,self.y)
  }

  public fun get_map_id(self: &Position): u64 {
    self.map_id
  }

  public fun get_x(self: &Position): u64 {
    self.x
  }

  public fun get_y(self: &Position): u64 {
    self.y
  }

  public(package) fun set_map_id(self: &mut Position, map_id: u64) {
    self.map_id = map_id;
  }

  public(package) fun set_x(self: &mut Position, x: u64) {
    self.x = x;
  }

  public(package) fun set_y(self: &mut Position, y: u64) {
    self.y = y;
  }

  public(package) fun set(self: &mut Position, map_id: u64, x: u64, y: u64) {
    self.map_id = map_id;
    self.x = x;
    self.y = y;
  }
}
