  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dubhe::dubhe_lp_burned_event {

  use sui::event;

  use std::ascii::String;

  use dubhe::dubhe_account_status::AccountStatus;

  use dubhe::dubhe_asset_status::AssetStatus;

  use dubhe::dubhe_asset_type::AssetType;

  use dubhe::dubhe_account::Account;

  use dubhe::dubhe_asset_metadata::AssetMetadata;

  use dubhe::dubhe_pool::Pool;

  use dubhe::dubhe_bridge_config::BridgeConfig;

  use dubhe::dubhe_dapp_metadata::DappMetadata;

  use dubhe::dubhe_dapp_stats::DappStats;

  public struct LpBurnedEvent has copy, drop {
    sender: address,
    asset0: u256,
    asset1: u256,
    amount0: u256,
    amount1: u256,
    to: address,
  }

  public fun new(
    sender: address,
    asset0: u256,
    asset1: u256,
    amount0: u256,
    amount1: u256,
    to: address,
  ): LpBurnedEvent {
    LpBurnedEvent {
                                   sender,asset0,asset1,amount0,amount1,to
                               }
  }
}
