  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module numeron::item_type {

  use sui::bcs::{BCS, to_bytes, peel_enum_tag};

  public enum ItemType has copy, drop, store {
        Ball,Currency,Food,Material,Medicine,Scroll,SkillBook,TreasureChest
    }

  public fun new_ball(): ItemType {
    ItemType::Ball
  }

  public fun new_currency(): ItemType {
    ItemType::Currency
  }

  public fun new_food(): ItemType {
    ItemType::Food
  }

  public fun new_material(): ItemType {
    ItemType::Material
  }

  public fun new_medicine(): ItemType {
    ItemType::Medicine
  }

  public fun new_scroll(): ItemType {
    ItemType::Scroll
  }

  public fun new_skillbook(): ItemType {
    ItemType::SkillBook
  }

  public fun new_treasurechest(): ItemType {
    ItemType::TreasureChest
  }

  public fun encode(self: ItemType): vector<u8> {
    to_bytes(&self)
  }

  public fun decode(bytes: &mut BCS): ItemType {
    match(peel_enum_tag(bytes)) {
            0 => ItemType::Ball,
            1 => ItemType::Currency,
            2 => ItemType::Food,
            3 => ItemType::Material,
            4 => ItemType::Medicine,
            5 => ItemType::Scroll,
            6 => ItemType::SkillBook,
            7 => ItemType::TreasureChest,
            _ => abort,
        }
  }
}
